### ISSUE TITLE
[Bug] `loguru`의 색상이 Kubernetes 환경에서 정상적으로 출력되지 않음

### ISSUE THREAD

**Issue by Zerohertz** [Zerohertz/fastapi-boilerplate#9]
### What happened?

아래와 같이 loguru의 색상이 정상적으로 출력되지 않음

<img width="2050" alt="Screenshot 2025-01-14 at 8 44 03 PM" src="https://github.com/user-attachments/assets/ab12a085-4bc2-4c17-85c6-af343445d213" />

**Comment by Zerohertz** [comment]
```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test
  name: test
spec:
  containers:
    - image: zerohertzkr/dev
      imagePullPolicy: Always
      command:
        - zsh
        - -c
        - source ~/.zshrc && pip install loguru && python -c 'import zerohertzLib; logger=zerohertzLib.logging.Logger(); logger.info("test"); from loguru import logger; import sys; logger.remove(); logger.add(sys.stderr, colorize=True); logger.info("test"); import time; time.sleep(100)'
      name: test
      env:
        - name: LOGURU_FORMAT
          value: "<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level: <8}</level> | <fg #800a0a>{name}</fg #800a0a>:<fg #800a0a>{function}</fg #800a0a>:<fg #800a0a>{line}</fg #800a0a> - <level>{message}</level>"
        # - name: "FORCE_COLOR"
        #   value: "1"
```

> [!NOTE]
> `FORCE_COLOR`는 `rich` logger와 같은 종류에 적용 시 필요

<img width="1037" alt="Screenshot 2025-01-14 at 8 56 43 PM" src="https://github.com/user-attachments/assets/60de7c4d-7fce-4647-8f3c-b813ca9c42d5" />
